### ISSUE TITLE
"New version" isn't always newer

### ISSUE THREAD

**Issue by bep** [psampaz/go-mod-outdated#1]
Great tool!

I notice in your examples that the "New version" isn't always newer than the version/revision on the left. I understand why it is so, but I think it is a little misleading -- as you would think that by updating to that version you will include the features in the left version.

**Comment by psampaz** [comment]
Thank you very much for the feedback. Can you please explain a little bit more your point so I can understand what I missing? Can you give me a specific example so I can check further?

According to the comments of the go list tool https://github.com/golang/go/blob/f1d5ce0185fe184c016016d55f1718778b799f6d/src/cmd/go/internal/list/list.go#L241:

> The -u flag adds information about available upgrades.
> **When the latest version of a given module is newer than
> the current one, list -u sets the Module's Update field
> to information about the newer module.**
> The Module's String method indicates an available upgrade by
> formatting the newer version in brackets after the current version.
> For example, 'go list -m -u all' might print:

So since this tool uses the output of the go list -m -u all I assume that when the Update field is set, there is an newer version.

For the misleading part, are you referring to non semantic versioned modules, where it is completely unclear if code was added or deleted or the newer module is compatible with the previous one (left side)?

If yes, do you thing a clarification in the README file is enough?

**Comment by bep** [comment]
>| github.com/muesli/smartcrop               | v0.0.0-20180228075044-f6ebaa786a12   | v0.2.0  

* https://github.com/muesli/smartcrop/commit/f6ebaa786a12 28 Feb 2018
* https://github.com/muesli/smartcrop/releases/tag/v0.2.0 11 Aug 2017

**Comment by georlav** [comment]
@bep Go modules relies on valid semver versions.
it looks like the example you provided is using invalid semver tags.

**Comment by bep** [comment]
As I said: I understand the **why** -- it's just that your tool would be much more useful if it could provide more accurate info. In the example above, one could think that upgrading to `0.2.0` would be the sensible thing to do (since it's "newer"), but it would break the application.

**Comment by psampaz** [comment]
@bep you are absolutely correct

go list -u -m all reports the following

```
{
	"Path": "github.com/muesli/smartcrop",
	"Version": "v0.0.0-20180228075044-f6ebaa786a12",
	"Time": "2018-02-28T07:50:44Z",
	"Update": {
		"Path": "github.com/muesli/smartcrop",
		"Version": "v0.2.0",
		"Time": "2017-08-09T19:13:04Z"
	},
	"GoMod": "/home/user/go/pkg/mod/cache/download/github.com/muesli/smartcrop/@v/v0.0.0-20180228075044-f6ebaa786a12.mod"
}
```

So the update is older than the current version.

The problem is that running

```
go get -u github.com/muesli/smartcrop
```

or 

```
go get -u=patch github.com/muesli/smartcrop
```

will actually update to github.com/muesli/smartcrop to 0.2.0 without any check on timestamp differences.

Which according to the go get help is normal 

```
By default, get chooses the latest tagged
release version, such as v0.4.5 or v1.2.3. If there are no tagged release
versions, get chooses the latest tagged prerelease version, such as
v0.0.1-pre1. If there are no tagged versions at all, get chooses the latest
known commit.
```

It seems that the go get tool should include a timestamp check and inform users on the possibility of breaking their application since I agree with @georlav that this is the outcome of invalid tags.

I will try to add an extra column indicating that what Go refers as an update is actually an on older version.
