### ISSUE TITLE
Prompt like npm-check

### ISSUE THREAD

**Issue by frederikhors** [psampaz/go-mod-outdated#14]
I love this tool. Thank you very much.

It would be amazing to have a prompt, something like https://github.com/dylang/npm-check:

![image](https://user-images.githubusercontent.com/41120635/60740957-0329d880-9f68-11e9-9043-b8dc1549b2b0.png)

So I can choose what to update.

**Comment by psampaz** [comment]
Hi, 

this seems very very interesting but it goes out of the scope of this tool which was built as a reporting/ci tool and not a tool to actually handle updates.

Adding functionality for updating packages (or other go modules operations) is much more complicated and requires close monitoring of the go modules development.

I would rather accept MR that introduces a -json flag to this tool, so that you can pipe the output to another dedicated tool that handle the updates.

**Comment by oligot** [comment]
Hi,

I'm also interested by this feature, and I've decided to implement it in a dedicated tool called go-mod-upgrade: https://github.com/oligot/go-mod-upgrade

Hoping that this is also useful for others.

**Comment by psampaz** [comment]
@oligot that's a great tool!

closing this one.
