### ISSUE TITLE
use as a package

### ISSUE THREAD

**Issue by BenKnigge** [psampaz/go-mod-outdated#39]
It would be nice if you could use the functionality inside of another application

all that would be required to make this happen is to remove or rename the internal directory.

**Comment by BenKnigge** [comment]
I've made the changes in the following pr but it looks like some of the integration tests need to be updated before it can be merged.

**Comment by BenKnigge** [comment]
https://github.com/psampaz/go-mod-outdated/pull/40

**Comment by psampaz** [comment]
Hi @BenKnigge,

thank you for opening this issue. Please note that the use of the internal folder was selected in first place in order to actually prevent using the code as a package. The purpose of this project is to be used as command line tool and not as a library. Therefore I would to kindly reject this. It is not that I do not find it useful. I just do not want to change the scope of this project. Maybe you could fork it and make a well maintained library only version.

**Comment by BenKnigge** [comment]
Will do.
